%% combo_show_communities

% combo_show_communities is a function that allows you to see the results
% of community detection. 
% 
% It relays on the assumptions:
% 
% - you have a set of N subjecjts
% - THose subjects might have a diagnosis (ej, Control or ADHD)
% - You have brain scores for each participant
%   - For example, if you have 4 scores, each participant will have 4
%   numbers, each corresponding to a brain score
%   - Those scores were used to calculate a distance matrix
%   - that distance matrix was used to identify communities
% - Community assignment (integer) is stored in a vector (idx). 
% - You have additional scores for each participant that were not used for
% community detection
%
%
% It generates 3 sets of figures:
%
% - Histograms showing the number of communities in one color and
% colorcoded by diagnosis
% - Distance matrices of the data used for community detection
% - Distributions of scores

%% Load example data
%
% Here you will load the following variables:
%
% - glabs, diagnosis for each participant
% - idx, a vector with community assignment
% - idx_truncated, a vector where small communities were merged as a unique
% community
% - T_brain_scores, table containing the brain scores used in community
% detection
% - T_behavioral_scores, table containing additional scores that were not
% used for community detection
fs=filesep;
load('C:\Users\oscar\OneDrive\matlab_code\plotting-tools\combo_show_communities\example_data\example_data.mat')
% 
%% Define additional arguments

% Define output folder
% Use this argument to define were to save the figures
output_folder=['C:\Users\oscar\OneDrive\matlab_code\plotting-tools\combo_show_communities' fs 'example_output'];

% Define path to table with colors to show
% Provide the path to a table saved in csv format where you define the RGB
% colors to be used to colorcode each group defined in the cell glabs (see
% provided table)
path_Group_Color_Table='C:\Users\oscar\OneDrive\matlab_code\plotting-tools\combo_show_communities\example_data\Group_Color_Table.csv';

% Degine which of the groups defined in the cell "glabs" will be shown
% Here you defined which groups to show (so far the code only works for 1
% or 2 groups)
glabs_to_show={'Control','ADHD'};

% define which normalization method to use
% Use this variable to normalize data (prefered boxcox, available options
% are: none, zscore, and boxcox
normalization_method='boxcox';

% Define which group you will use as reference when normalizing scores
% Self-descriptive
glab_reference='Control';

% Define behavioral scores to show
% Define which headers to show from the T_behavioral_scores
clear behav_to_show
ix=0;
ix=ix+1;behav_to_show{ix}='adhd comp.';
ix=ix+1;behav_to_show{ix}='adhd prs';
ix=ix+1;behav_to_show{ix}='int comp.';
% ix=ix+1;behav_to_show{ix}='SWAN_INT';
ix=ix+1;behav_to_show{ix}='hyp comp.';
% ix=ix+1;behav_to_show{ix}='SWAN_HYP';

% Define resolution to save figures
res=300;

% external_cmap
% Use this variable to define which colormap to use. Use empty (as shown in
% the example) to use the colormap automatically generated by the code.
% Additionally, you could use external_cmap='jet', or
% external_cmap='parula'
external_cmap=[];
%% Run the example

combo_show_communities (T_brain_scores,...
    T_behavioral_scores,...
    idx,...
    glabs,...
    'output_folder',output_folder,...
    'path_Group_Color_Table',path_Group_Color_Table,...
    'external_cmap',external_cmap,...
    'idx_truncated',idx_truncated,...
    'glabs_to_show',glabs_to_show,...
    'glab_reference',glab_reference,...
    'behav_to_show',behav_to_show,...
    'normalization_method',normalization_method)

%%
% Oscar Miranda-Dominguez,
% Feb 26, 2022