function text=text_after_reading_path(handles)

text=['There are '...
    num2str(handles.participants.N) ' individual studies listed in this file.',...
' Based on the naming using in the file, the data comes from ',...
num2str(handles.participants.unique_ids) ' unique ids and has been processed using ',...
num2str(handles.participants.unique_pipelines) ' pipeline(s).'];
