function add_th_lines_y_axis(neg_log10_max_P,...
    th_names)

xl=xlim;
line_color=[1 1 1]*.4;
line_style='-';
line_width=.1;
n_th=numel(neg_log10_max_P);
fs=7;
for i=1:n_th
    line(xl,neg_log10_max_P([i i]),...
        'color',line_color,...
        'LineStyle',line_style,...
        'Linewidth',line_width);
    
    t=text(xl(2),neg_log10_max_P(i),th_names{i},...
        'HorizontalAlignment','left',...
        'VerticalAlignment','Middle',...
        'Fontsize',fs);
%     t.BackgroundColor=[1 1 1];
end