%% add paths
addpath(genpath('C:\Users\oscar\OneDrive\matlab_code'));

%%
wd='C:\Users\oscar\OneDrive\matlab_code\fconn_matrices_tools\parcel_HCP_ColeAnticevic_wSubcorGSR';
%%
fs=filesep;

%% PAth to label file

path_dlabel=[wd fs 'CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR.dlabel.nii'];

%% This section reads the label file and save ROIs as text file

tidyTable_filename=[pwd fs 'HCP_ColeAnticevic_wSubcorGSR_temp'];
tidyTable=dlabel_to_tidyTable(path_dlabel,tidyTable_filename);
%% 
% tidyTable_filename was used by Anjani to make the corresponding
% HCP_ColeAnticevic_wSubcorGSR.csv
path_parcellation_table=[wd fs 'HCP_ColeAnticevic_wSubcorGSR.csv'];
parcel=loadParcel(path_parcellation_table);

save('HCP_ColeAnticevic_wSubcorGSR.mat','parcel')

%%
F1=showM(M,...
'parcel',parcel,...
'line_color',[0 0 0],...
'line_width',0.5,...
'fs_axis',10,...
'fig_wide',7,...
'one_side_labels',1,...
'fig_tall',8);
 print(['HCP_ColeAnticevic_wSubcorGSR_BY_NETORKS'],'-dpng','-r300')
F2=showM(M,...
'line_color',[0 0 0],...
'line_width',0.5,...
'fs_axis',10,...
'fig_wide',7,...
'one_side_labels',1,...
'fig_tall',8);
print(['HCP_ColeAnticevic_wSubcorGSR'],'-dpng','-r300')