path_imaging='C:\Users\oscar\OneDrive\matlab_code\polyneuro_risk_score\data\xsectional_1_outcome_fconn\fconn.mat';
path_betaweights='C:\Users\oscar\Downloads\CWAS\fconn_xsectional_lutein\case3_prewhitening\tables\brain_feature.csv';
output_folder=['C:\Users\oscar\Downloads\PVS\fconn_xsectional_lutein' filesep 'case3_no_covariates'];



PBScores=run_PBS(path_imaging,path_betaweights,...
    'output_folder',output_folder);

%%

path_demographics_Table='C:\Users\oscar\OneDrive\matlab_code\polyneuro_risk_score\data\xsectional_1_outcome_fconn\demographcis_Table.csv';
path_dictionary_demographics_Table='C:\Users\oscar\OneDrive\matlab_code\polyneuro_risk_score\data\xsectional_1_outcome_fconn\Dictionary_for_demographics_Table.csv';
path_group_Design_Table='C:\Users\oscar\OneDrive\matlab_code\polyneuro_risk_score\data\xsectional_1_outcome_fconn\Group_Design_Table.csv';


PBScores=run_PBS(path_imaging,path_betaweights,...
    'output_folder',output_folder,...
    'path_demographics_Table',path_demographics_Table,...
    'path_dictionary_demographics_Table',path_dictionary_demographics_Table,...
    'path_group_Design_Table',path_group_Design_Table);

%%
path_Group_Color_Table ='C:\Users\oscar\OneDrive\matlab_code\polyneuro_risk_score\data\xsectional_1_outcome_fconn\Group_Color_Table.csv';
PBScores=run_PBS(path_imaging,path_betaweights,...
    'output_folder',output_folder,...
    'path_demographics_Table',path_demographics_Table,...
    'path_dictionary_demographics_Table',path_dictionary_demographics_Table,...
    'path_group_Design_Table',path_group_Design_Table,...
    'path_Group_Color_Table',path_Group_Color_Table);